# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from apitest import calculate_love
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(409, 270)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 110, 291, 61))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(110, 60, 281, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(110, 10, 281, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 371, 51))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 110, 81, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 409, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        self.pushButton.clicked.connect(self.on_click_calculate)

        self.pushButton_2.clicked.connect(self.clear)

    def on_click_calculate(self):
        value1 = self.textEdit.text()
        value2 = self.textEdit_2.text()
        if value1 != "" and value2 != "":
            self.label_3.setText(calculate_love(value1, value2))
        else:
            self.label_3.setText("Make sure you filled both input fields")

    def clear(self):
        self.textEdit.setText("")
        self.textEdit_2.setText("")
        self.label_3.setText("Enter two name and click the button.")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LoveCalculator"))
        self.pushButton.setText(_translate("MainWindow", "Calculate Love"))
        self.label.setText(_translate("MainWindow", "   Name 1 "))
        self.label_2.setText(_translate("MainWindow", "   Name 2"))
        self.label_3.setText(_translate("MainWindow", "Enter two name and click the button."))
        self.pushButton_2.setText(_translate("MainWindow", "Reset"))
        
        
        self.label.setStyleSheet("color: black")
        self.label_2.setStyleSheet("color: black")  
        self.label_3.setStyleSheet("color: black")  
        self.textEdit.setStyleSheet("color: black")
        self.textEdit_2.setStyleSheet("color: black")
        self.centralwidget.setStyleSheet("background-color: pink")  

        # self.label_2.setStyleSheet("background-color: red")  
        # self.pushButton.setStyleSheet("background-color: pink; border: 1px solid black")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
